### ISSUE TITLE
nodegui-starter example failure to install 

### ISSUE THREAD

**Issue by tomwbarclay** [nodegui/nodegui-starter#145]
command 'npm install' fails when it cant find pre-built Windows file ... see below. 

**prebuild-install GET https://github.com/nodegui/nodegui/releases/download/v0.24.0/nodegui-v0.24.0-napi-v3-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=x64 libc= platform=win32)**

when script executes

prebuild-install --backend=cmake-js --runtime=napi --verbose.

Looked at GitHub and 'releases' folder non existant. 

Presumably on Linux the install script compiles the required binaries from raw. 

Am I better of using Linux ?

**Comment by a7ul** [comment]
This one is just a warning actually. If it cant detect the prebuilt files it will continue to do the actual build. 

You should have the actual log in the end

**Comment by tomwbarclay** [comment]
Problem was red herring ... script continued past that error, it was just the first error in the execution order so I thought it was significant.

Installed VisualStudio2019 community editionm and re-run the install. The script still fails at same point but when it continues it now builds from the cpp files for the QT wrappers etc. At end a 'npm audit fix' command sorts last issues. 

Execute the example with'npm  start'  and the example runs OK. ... Thanks
