### ISSUE TITLE
Error during npm start, undefined symbol: _ZdlPvm, version Qt_5

### ISSUE THREAD

**Issue by ksnortum** [nodegui/nodegui-starter#229]
I get this output executing `npm start`:

    > nodegui-starter@1.0.0 start
    > webpack && qode ./dist/index.js

    asset nodegui_core-290f6c2c05e3b47bcedc55c3bd1078e0.node 8.86 MiB [emitted] (auxiliary name: main)
    asset index.js 1.43 MiB [emitted] (name: main)
    asset 22c8769d0d1e03941f73a69e7842ebe4.png 6.58 KiB [emitted] [immutable] [from: assets/logox200.png] (auxiliary name: main)
    runtime modules 670 bytes 3 modules
    modules by path ./node_modules/@nodegui/nodegui/dist/lib/ 590 KiB 231 modules
    modules by path ./node_modules/postcss/lib/*.js 480 KiB
      ./node_modules/postcss/lib/postcss.js 18.7 KiB [built] [code generated]
      ./node_modules/postcss/lib/declaration.js 6.21 KiB [built] [code generated]
      + 23 modules
    modules by path ./node_modules/source-map/ 99.4 KiB
      ./node_modules/source-map/source-map.js 405 bytes [built] [code generated]
      ./node_modules/source-map/lib/source-map-generator.js 14 KiB [built] [code generated]
      + 9 modules
    modules by path ./node_modules/cuid/ 2.88 KiB
      ./node_modules/cuid/index.js 2.18 KiB [built] [code generated]
      ./node_modules/cuid/lib/fingerprint.js 435 bytes [built] [code generated]
      + 2 modules
    + 13 modules
    webpack 5.74.0 compiled successfully in 1535 ms
    Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
    /home/knute/git-repos/nodegui-starter/node_modules/@nodegui/qode/binaries/qode: symbol lookup error: /home/knute/git-repos/nodegui-starter/dist/nodegui_core-290f6c2c05e3b47bcedc55c3bd1078e0.node: undefined symbol: _ZdlPvm, version Qt_5

I'm on Ubuntu 22.04.1.

uname -a

    Linux *****-NUC11PAHi7 5.15.0-52-lowlatency #58-Ubuntu SMP PREEMPT Thu Oct 13 12:37:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

I've tried it with the standard `node` I get with `atp install`: v12.22.9, and downloading the latest from github: v18.12.1

Any other info needed?

**Comment by nicro** [comment]
Having same issue with fedora 22.1
