### ISSUE TITLE
When running "npm start", an error regardig "xcb" is thrown

### ISSUE THREAD

**Issue by C0braD3v** [nodegui/nodegui-starter#44]
When cloning this repository, installing dependencies, and running "npm start" This error is thrown:

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

This occurs with no changes to index.ts or any other files.

**Comment by C0braD3v** [comment]
This issue is occurring on WSL Ubuntu, when run on Poweshell this error is revived:
```
'webpack' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegui-starter@1.0.0 start: `webpack && qode ./dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegui-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

NPM log of this error:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle nodegui-starter@1.0.0~prestart: nodegui-starter@1.0.0
6 info lifecycle nodegui-starter@1.0.0~start: nodegui-starter@1.0.0
7 verbose lifecycle nodegui-starter@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle nodegui-starter@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecy$9 verbose lifecycle nodegui-starter@1.0.0~start: CWD: C:\Users\hrpbu\DOCUMENTS\goUITest\nodegui-starter
10 silly lifecycle nodegui-starter@1.0.0~start: Args: [ '/d /s /c', 'webpack && qode ./dist/index.js' ]
11 silly lifecycle nodegui-starter@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle nodegui-starter@1.0.0~start: Failed to exec start script
13 verbose stack Error: nodegui-starter@1.0.0 start: `webpack && qode ./dist/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\i$13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\l$13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid nodegui-starter@1.0.0
15 verbose cwd C:\Users\hrpbu\DOCUMENTS\goUITest\nodegui-starter
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "$18 verbose node v12.14.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error nodegui-starter@1.0.0 start: `webpack && qode ./dist/index.js`
22 error Exit status 1
23 error Failed at the nodegui-starter@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]```

**Comment by master-atul** [comment]
Could you delete your node_modules once and re install using `npm install` in the powershell itself ? Webpack not found usually means something went wrong during dependency installation.

**Comment by master-atul** [comment]
Also WSL Ubuntu is not supported. You will need to use powershell when in windows.

**Comment by C0braD3v** [comment]
Yes I realized that, tried with PowerShell, and this is why I gave the Poweshell error as well. I will reinstall node modules and close if the issue is resolved.
