### ISSUE TITLE
Is this supposed to build on windows?

### ISSUE THREAD

**Issue by jpwhiting** [nodegui/nodegui-starter#45]
Thanks for putting this project together. I like the idea of it combining JavaScript with Qt gui widgets. However when I try to build nodegui-starter on windows 10 with nodejs 12.16.0 (and python, chocolatey, and visual studio that the installer pulls in), and cmake 3.16.4 on a fresh microsoft edge vm I get errors when npm install tries to build nodegui itself. I've attached the log. It seems like nodegui is failing to compile some functions that take an int as a parameter, it has possible conversions to uint32_t, std::string and char*.

I'm a bit new to nodejs, but after npm install fails, the whole @nodegui folder is gone to check/modify/fix the build issue. I guess I would need to fix it in nodegui itself, get a new release of nodegui, and make nodegui-starter depend on that new version to get the fix?

[install.log](https://github.com/nodegui/nodegui-starter/files/4207551/install.log)

**Comment by master-atul** [comment]
Hi @jpwhiting 

What is the node version you are using?
What is the operating system - is it a 32bit or a 64bit OS ?

**Comment by jpwhiting** [comment]
It's a 64 bit windows 10 vm. Maybe I have the wrong build of node.js? I did the 32 bit build for backwards compatibility. I'll try the 64 bit node.js.

**Comment by jpwhiting** [comment]
Yep, that solved it. Thanks for the pointer.
