### ISSUE TITLE
🐛 Bug: npm install fails on windows 10

### ISSUE THREAD

**Issue by supercoww** [nodegui/nodegui-starter#79]
**Describe the bug**
npm install fails at the post-install step on windows 10

**To Reproduce**
1. On windows 10, open Powershell.
2. Run:
```powershell
git clone https://github.com/nodegui/nodegui-starter
cd nodegui-starter
npm install
```
3. See error

**Expected behavior**
Dependencies should be installed without any errors.

**Logs**
```

> @nodegui/qode@2.0.4 postinstall D:\nodegui-starter\node_modules\@nodegui\qode
> node install.js

Cached archive already exists at C:\Users\ambar_ywm83\AppData\Local\qode-nodejs\Cache\qode-win32-x64-v2.0.4.tar.gz. Ski
pping download....
Extracting C:\Users\ambar_ywm83\AppData\Local\qode-nodejs\Cache\qode-win32-x64-v2.0.4.tar.gz to D:\nodegui-starter\node
_modules\@nodegui\qode\binaries ...
Qode was setup successfully at : D:\nodegui-starter\node_modules\@nodegui\qode\binaries

> @nodegui/nodegui@0.16.1 postinstall D:\nodegui-starter\node_modules\@nodegui\nodegui
> cross-env npm run setupqt && (node ./scripts/skip.js || npm run prebuild:install || npm run build:addon)


> @nodegui/nodegui@0.16.1 setupqt D:\nodegui-starter\node_modules\@nodegui\nodegui
> cross-env node ./scripts/setupMiniQt.js

Minimal Qt 5.14.1 setup:
Archive already exists at C:\Users\ambar_ywm83\AppData\Local\nodegui-mini-qt-nodejs\Cache\5.14.1-0-202001240957qtbase-W
indows-Windows_10-MSVC2017-Windows-Windows_10-X86_64.7z. Skipping download....
Extracting C:\Users\ambar_ywm83\AppData\Local\nodegui-mini-qt-nodejs\Cache\5.14.1-0-202001240957qtbase-Windows-Windows_
10-MSVC2017-Windows-Windows_10-X86_64.7z to D:\nodegui-starter\node_modules\@nodegui\nodegui\miniqt ...
Error: Exited with code 2
    at ChildProcess.<anonymous> (D:\nodegui-starter\node_modules\7zip-min\index.js:56:19)
    at ChildProcess.emit (events.js:311:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.16.1 setupqt: `cross-env node ./scripts/setupMiniQt.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/nodegui@0.16.1 setupqt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ambar_ywm83\AppData\Roaming\npm-cache\_logs\2020-04-07T15_38_49_446Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.16.1 postinstall: `cross-env npm run setupqt && (node ./scripts/skip.js || npm run prebuild:install || npm run build:addon)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/nodegui@0.16.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ambar_ywm83\AppData\Roaming\npm-cache\_logs\2020-04-07T15_38_50_435Z-debug.log
```

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10
 - NodeGui version 0.16.1
 - OS Version [Version 10.0.18363.693]

**Comment by master-atul** [comment]
Looks like a the file was partially downloaded and when it tried to extract it failed
You can try deleting this directory 
```C:\Users\ambar_ywm83\AppData\Local\nodegui-mini-qt-nodejs\```
 and node_modules folder of the starter
and do npm install  @supercoww

**Comment by supercoww** [comment]
> Looks like a the file was partially downloaded and when it tried to extract it failed
This was the issue. Thanks for the help.

**Comment by KasimAliTatagar** [comment]
Hi ,
Get an error while installing ,

@nodegui/nodegui@0.24.0 prebuild:install C:\Users\ekastat\Desktop\My_nodejs\GUI_app\node_modules\@nodegui\nodegui
> prebuild-install --backend=cmake-js --runtime=napi --verbose

prebuild-install info begin Prebuild-install version 5.3.5
prebuild-install info looking for cached prebuild @ C:\Users\ekastat\AppData\Roaming\npm-cache\_prebuilds\ab258d-nodegui-v0.24.0-napi-v3-win32-x64.tar.gz
prebuild-install http request GET https://github.com/nodegui/nodegui/releases/download/v0.24.0/nodegui-v0.24.0-napi-v3-win32-x64.tar.gz
prebuild-install http 404 https://github.com/nodegui/nodegui/releases/download/v0.24.0/nodegui-v0.24.0-napi-v3-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=x64 libc= platform=win32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.24.0 prebuild:install: `prebuild-install --backend=cmake-js --runtime=napi --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/nodegui@0.24.0 prebuild:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ekastat\AppData\Roaming\npm-cache\_logs\2020-07-19T07_48_38_890Z-debug.log

> @nodegui/nodegui@0.24.0 build:addon C:\Users\ekastat\Desktop\My_nodejs\GUI_app\node_modules\@nodegui\nodegui
> cross-env CMAKE_BUILD_PARALLEL_LEVEL=8 cmake-js compile

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'bluebird'
Require stack:
- C:\Users\ekastat\Desktop\My_nodejs\GUI_app\node_modules\cmake-js\lib\downloader.js
- C:\Users\ekastat\Desktop\My_nodejs\GUI_app\node_modules\cmake-js\lib\dist.js
- C:\Users\ekastat\Desktop\My_nodejs\GUI_app\node_modules\cmake-js\lib\cMake.js
- C:\Users\ekastat\Desktop\My_nodejs\GUI_app\node_modules\cmake-js\lib\buildSystem.js
- C:\Users\ekastat\Desktop\My_nodejs\GUI_app\node_modules\cmake-js\lib\index.js
- C:\Users\ekastat\Desktop\My_nodejs\GUI_app\node_modules\cmake-js\bin\cmake-js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\ekastat\Desktop\My_nodejs\GUI_app\node_modules\cmake-js\lib\downloader.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\ekastat\\Desktop\\My_nodejs\\GUI_app\\node_modules\\cmake-js\\lib\\downloader.js',
    'C:\\Users\\ekastat\\Desktop\\My_nodejs\\GUI_app\\node_modules\\cmake-js\\lib\\dist.js',
    'C:\\Users\\ekastat\\Desktop\\My_nodejs\\GUI_app\\node_modules\\cmake-js\\lib\\cMake.js',
    'C:\\Users\\ekastat\\Desktop\\My_nodejs\\GUI_app\\node_modules\\cmake-js\\lib\\buildSystem.js',
    'C:\\Users\\ekastat\\Desktop\\My_nodejs\\GUI_app\\node_modules\\cmake-js\\lib\\index.js',
    'C:\\Users\\ekastat\\Desktop\\My_nodejs\\GUI_app\\node_modules\\cmake-js\\bin\\cmake-js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.24.0 build:addon: `cross-env CMAKE_BUILD_PARALLEL_LEVEL=8 cmake-js compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/nodegui@0.24.0 build:addon script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ekastat\AppData\Roaming\npm-cache\_logs\2020-07-19T07_48_44_189Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN nodegui-starter@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.24.0 postinstall: `cross-env npm run setupqt && (node ./scripts/skip.js || npm run prebuild:install || npm run build:addon)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/nodegui@0.24.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ekastat\AppData\Roaming\npm-cache\_logs\2020-07-19T07_48_49_261Z-debug.log

C:\Users\ekastat\Desktop\My_nodejs\GUI_app>
