### ISSUE TITLE
Downloading Qode is Slow

### ISSUE THREAD

**Issue by harindaka** [nodegui/nodegui-starter#84]
When I run `npm install` the `Downloading Qode` start takes forever. It's been more than an hour now but its still downloading. It does progress though. Is there an alternative way to download this and set it up?

**Comment by master-atul** [comment]
Thats interesting. Qode is currently hosted in github releases. 
You can try and download it and paste it on the location shown on the terminal.

**Comment by harindaka** [comment]
@master-atul seems to download fast from my vps located in US. Must be region or ISP related as I'm outside US
