### ISSUE TITLE
NPM install fails during install Download of Qt Base for Minimal Qt

### ISSUE THREAD

**Issue by krishnapavankumar** [nodegui/nodegui-starter#94]
```
Minimal Qt 5.14.1 setup:
Error: Error while downloading Qt Base for Minimal Qt: 5.14.1 installation:https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5141/qt.qt5.5141.win64_msvc2017_64/5.14.1-0-202001240957qtbase-Windows-Windows_10-MSVC2017-Windows-Windows_10-X86_64.7z. Forbidden
```

I tried removing a folder of this in AppData and tried again and still same issue

**Comment by krishnapavankumar** [comment]
I removed npm-cache folder in AppData/local and tried doing npm install again and now it is successfully ran setup for Minimal Qt


>Qt Base for Minimal Qt: 5.14.1 installation was setup successfully.  outDir: C:\Users\polisetp\Documents\Persona\NODE GUI\Basic\react-nodegui-starter\node_modules\@nodegui\nodegui\miniqt

But failed at the next step

> @nodegui/nodegui@0.16.1 prebuild:install C:\Users\polisetp\Documents\Persona\NODE GUI\Basic\react-nodegui-starter\node_modules\@nodegui\nodegui
> prebuild-install --backend=cmake-js --runtime=napi --verbose
> 
> prebuild-install info begin Prebuild-install version 5.3.3
> prebuild-install info looking for cached prebuild @ C:\Users\polisetp\AppData\Roaming\npm-cache\_prebuilds\fc7405-nodegui-v0.16.1-napi-v3-win32-x64.tar.gz
> prebuild-install http request GET https://github.com/nodegui/nodegui/releases/download/v0.16.1/nodegui-v0.16.1-napi-v3-win32-x64.tar.gz
> prebuild-install http 404 https://github.com/nodegui/nodegui/releases/download/v0.16.1/nodegui-v0.16.1-napi-v3-win32-x64.tar.gz
> prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=x64 libc= platform=win32)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @nodegui/nodegui@0.16.1 prebuild:install: `prebuild-install --backend=cmake-js --runtime=napi --verbose`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @nodegui/nodegui@0.16.1 prebuild:install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\polisetp\AppData\Roaming\npm-cache\_logs\2020-05-12T05_04_45_249Z-debug.log

Guide me to resolve it soon as I have been waiting for this from 2 weeks

**Comment by master-atul** [comment]
This doesn't look like the complete log. The error you see above can be ignored as it is just missing the prebuild, NodeGui should then be automatically built. 

Please delete your node_module and install again.
And then post the complete logs here.

**Comment by krishnapavankumar** [comment]
Here is the full log after removing node_modules folder and doing npm_install


```
C:\Users\Krishnap\Documents\Persona\NODE GUI\Basic\react-nodegui-starter npm install

  @nodegui/qode@2.0.4 postinstall C:\Users\Krishnap\Documents\Persona\NODE GUI\Basic\react-nodegui-starter\node_modules\@nodegui\qode
  node install.js

Cached archive already exists at C:\Users\Krishnap\AppData\Local\qode-nodejs\Cache\qode-win32-x64-v2.0.4.tar.gz. Skipping download....
Extracting C:\Users\Krishnap\AppData\Local\qode-nodejs\Cache\qode-win32-x64-v2.0.4.tar.gz to C:\Users\Krishnap\Documents\Persona\NODE GUI\Basic\react-nodegui-starter\node_modules\@nodegui\qode\binaries ...
Qode was setup successfully at : C:\Users\Krishnap\Documents\Persona\NODE GUI\Basic\react-nodegui-starter\node_modules\@nodegui\qode\binaries

  @nodegui/nodegui@0.16.1 postinstall C:\Users\Krishnap\Documents\Persona\NODE GUI\Basic\react-nodegui-starter\node_modules\@nodegui\nodegui
  cross-env npm run setupqt && (node ./scripts/skip.js || npm run prebuild:install || npm run build:addon)


  @nodegui/nodegui@0.16.1 setupqt C:\Users\Krishnap\Documents\Persona\NODE GUI\Basic\react-nodegui-starter\node_modules\@nodegui\nodegui
  cross-env node ./scripts/setupMiniQt.js

Minimal Qt 5.14.1 setup:
Error: Error while downloading Qt Tools for Minimal Qt: 5.14.1 installation:https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5141/qt.qt5.5141.win64_msvc2017_64/5.14.1-0-202001240957qttools-Windows-Windows_10-MSVC2017-Windows-Windows_10-X86_64.7z. Forbidden
    at Object.<anonymous  (C:\Users\Krishnap\Documents\Persona\NODE GUI\Basic\react-nodegui-starter\node_modules\@nodegui\nodegui\node_modules\@nodegui\artifact-installer\dist\downloader.js:69:31)
    at step (C:\Users\Krishnap\Documents\Persona\NODE GUI\Basic\react-nodegui-starter\node_modules\@nodegui\nodegui\node_modules\@nodegui\artifact-installer\dist\downloader.js:33:23)
    at Object.next (C:\Users\Krishnap\Documents\Persona\NODE GUI\Basic\react-nodegui-starter\node_modules\@nodegui\nodegui\node_modules\@nodegui\artifact-installer\dist\downloader.js:14:53)
    at fulfilled (C:\Users\Krishnap\Documents\Persona\NODE GUI\Basic\react-nodegui-starter\node_modules\@nodegui\nodegui\node_modules\@nodegui\artifact-installer\dist\downloader.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.16.1 setupqt: `cross-env node ./scripts/setupMiniQt.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/nodegui@0.16.1 setupqt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Krishnap\AppData\Roaming\npm-cache\_logs\2020-05-12T08_37_45_891Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.16.1 postinstall: `cross-env npm run setupqt && (node ./scripts/skip.js || npm run prebuild:install || npm run build:addon)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodegui/nodegui@0.16.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Krishnap\AppData\Roaming\npm-cache\_logs\2020-05-12T08_37_47_900Z-debug.log
```

**Comment by master-atul** [comment]
Can you see if you can download 
https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5141/qt.qt5.5141.win64_msvc2017_64/5.14.1-0-202001240957qttools-Windows-Windows_10-MSVC2017-Windows-Windows_10-X86_64.7z

manually ?

**Comment by krishnapavankumar** [comment]
No. Not able to do that download.
Restricted by my organization. 

Is there any alternative for me then?

**Comment by master-atul** [comment]
Yep, can you install Qt on your pc manually 
and then once you have done that 
set an environment variable QT_INSTALL_DIR=<path to your qt installation>/msvc2017  folder
then just delete your node_modules and npm install again.

**Comment by master-atul** [comment]
This will skip Qt download and use the Qt you have installed

**Comment by master-atul** [comment]
I am going to close this issue. But feel free to reach back here if that works or not works.
